name: Destroy AWS Resources

on:
  workflow_dispatch:

jobs:
  delete_aws_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo "Welcome to delete resources"
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::154989417037:role/GithubAdminRole
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy
        working-directory: ./terraform